account/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth.decorators import login_required
from account.views import profile, login

app_name = 'account'

urlpatterns = [
    path('', login_required(profile.ProfileView.as_view(), login_url='landing:landing'), name='profile'),
    path('login/', login.LoginView.as_view(), name='login')
]

landing/urls.py
from django.contrib import admin
from django.urls import path
from landing.views import landing, tarifs

app_name = 'landing'

urlpatterns = [
    path('', landing.AppView.as_view(), name='landing'),
    path('tarifs/', tarifs.TarifsView.as_view(), name='tarifs')
]

memorica/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    path('profile/', include('account.urls')),
    path('practice/', include('traning.urls')),
]

traning/urls.py
from django.contrib import admin
from django.urls import path
from traning.views import main, games

app_name = 'traning'

urlpatterns = [
    path('', main.MainView.as_view(), name='traning'),
    path('alphabet/', main.AlphabetView.as_view(), name='alphabet'),
    path('sounds/', main.SoundsView.as_view(), name='sounds'),
    path('games/alphabet/', games.GameAlphabetView.as_view(), name='game-alphabet')
]

account/models.py
from django.db import models
import uuid
from django.contrib.auth.models import AbstractUser, Permission, Group
from django.utils.translation import gettext_lazy as _
from account.managers import AccountManager

class Role(models.Model):
    name = models.CharField(max_length=50, unique=True)
    permissions = models.ManyToManyField(Permission)

    class Meta:
        verbose_name = _('role')
        verbose_name_plural = _('roles')

    def __str__(self):
        return self.name


class Account(AbstractUser):
    id = models.AutoField(primary_key=True)
    uid = models.UUIDField(unique=True, editable=False, default=uuid.uuid4)
    username = None
    email = models.EmailField(_('Адрес электронной почты'), unique=True)
    patronymic = models.CharField(_("Отчество"), max_length=60, null=True, blank=True)
    
    objects = AccountManager()

    roles = models.ManyToManyField(
        Role,
        verbose_name=_('roles'),
        blank=True,
        related_name='accounts'
    )

    groups = models.ManyToManyField(
        Group,
        verbose_name=_('groups'),
        blank=True,
        related_name='account_groups'
    )
    user_permissions = models.ManyToManyField(
        Permission,
        verbose_name=_('user permissions'),
        blank=True,
        related_name='account_user_permissions'
    )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []


class Child(models.Model):
    uid = models.UUIDField(unique=True, editable=False, default=uuid.uuid4)
    name = models.CharField(_("Имя ребенка"), max_length=50)
    birth_date = models.DateField(_("Дата рождения"), auto_now=False, auto_now_add=False)
    parent = models.ForeignKey(Account, verbose_name=_("Родитель"), on_delete=models.CASCADE)


class Balance(models.Model):
    user = models.OneToOneField(Account, on_delete=models.CASCADE)
    balance = models.IntegerField(default=10)

    def __str__(self):
        return f"Баланс - Пользователь: {self.user.username}, Balance: {self.balance}"

class Transaction(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    amount = models.IntegerField()
    timestamp = models.DateTimeField(auto_now_add=True)

traning/models.py
from django.db import models
import uuid
from django.utils.translation import gettext_lazy as _
from account.models import Account

class Ages(models.Model):
    AGE_1 = '3 года'
    AGE_2 = '4 года'
    AGE_3 = '5 лет'
    AGE_4 = '6 лет'
    AGE_5 = '7лет'

    AGE_CHOICES = [
        (AGE_1, '3 года'),
        (AGE_2, '4 года'),
        (AGE_3, '5 лет'),
        (AGE_4, '6 лет'),
        (AGE_5, '7 лет')
    ]

    age_name = models.CharField(max_length=20, choices=AGE_CHOICES)

class Game(models.Model):
    uid = models.UUIDField(unique=True, editable=False, default=uuid.uuid4)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    result = models.IntegerField(null=True)
    age = models.ForeignKey(Ages, verbose_name=_("Возраст"), on_delete=models.CASCADE)
    

    def __str__(self):
        return f"Игра #{self.id} - Пользователь: {self.user.username}, Результат: {self.result}, Возраст: {self.age}"

account/views.py
from django.shortcuts import render

# Create your views here.

account/views/login.py
from django.views.generic import View
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib import messages

class LoginView(View):
    template_name = 'app.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)
    
    def post(self, request, *args, **kwargs):
        email = request.POST.get('email')
        password = request.POST.get('password')

        user = authenticate(request, username=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('account:profile')
        else:
            messages.error(request, 'Неправильный email или пароль')
        return redirect(request.META.get('HTTP_REFERER'))

account/views/profile.py
from django.views.generic import View
from django.shortcuts import render, redirect

class ProfileView(View):
    template_name = 'account/profile.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

landing/views/landing.py
from django.views.generic import View
from django.shortcuts import render, redirect

class AppView(View):
    template_name = 'landing/base.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

landing/views/tarifs.py
from django.views.generic import View
from django.shortcuts import render, redirect

class TarifsView(View):
    template_name = 'landing/tarifs/tarifs.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

traning/views/games.py
from django.views.generic import View
import random
import string
from traning.models import Game, Ages
from django.http import JsonResponse
from django.shortcuts import render, redirect

class GameAlphabetView(View):
    template_name = 'traning/games/alphabet.html'

    def get(self, request, *args, **kwargs):
        letters = list(string.ascii_uppercase)
        correct_letter = random.choice(letters)
        random_letters = random.sample(letters, 3)
        options = random_letters + [correct_letter]
        random.shuffle(options)
        context = {'letters': options, 'correct_letter': correct_letter}
        return render(request, self.template_name, context)
    
    
    def post(self, request):
        selected_letter = request.POST.get('letter')
        letters = list(string.ascii_uppercase)  # Буквы кириллицы алфавита
        correct_letter = random.choice(letters)  # Случайная буква из letters
        correct = (selected_letter == correct_letter)
        return JsonResponse({'correct': correct})

landing/templates/landing/base.html
{% extends 'app.html' %}
{% block header %}
{% include './header.html' %}
{% endblock header %}

landing/templates/landing/header.html
{% load static %}
<div class="header__container">
    <div class="container">
        <div class="header__container-row">
            <div class="header__container-left">
                <div class="header__container-title">
                    <h1>Лучший способ научить ребенка читать</h1>

                    <article>Подходит для детей от 3-х лет<br>
                        Игры, интерактинвые задания.<br>
                        Все задания озвучены.
                    </article>

                    <a class="button orange" href="{% url 'traning:traning' %}">Начать заниматься</a>
                </div>
            </div>
            <div class="header__container-right">
                <img src="{% static 'img/duck_main.svg' %}" alt="">
            </div>
        </div>
    </div>
</div>

landing/templates/landing/tarifs/tarifs.html
{% extends 'app.html' %}
{% load static %}
{% block tarifs %}
<div class="tarifs__header">
    <div class="container">
        <h1>Учитесь читать без ограничения</h1>
        <div class="tarifs__header-banner">
            <img class="tarifs_banner" src="{% static 'img/tarifs_banner.svg' %}" alt="">
            <div class="banner__column">
            <h1>Скидка для новых пользователей</h1>
            <span>-50 %</span>
        </div>
        </div>
        </div>
</div>
<div class="tarifs__body">
    <div class="container">
        <div class="tarifs__body-row">
            <div class="tarifs__body-space">
            <div class="tarif__element">
                <div class="tarif__element-header">
                <h1>1 месяц</h1>
                </div>
                <div class="tarif__element-body">
                    <span>Безлимитный доступ ко всем упражнениям и разделам</span>
                    <span>580 Р</span>
                    <h1>290 Р</h1>
                </div>
            </div>
            <a href="!#" class="button">Оплатить</a>
        </div>
        <div class="tarifs__body-space">
            <div class="border">
            <div class="tarif__element">
                <div class="tarif__element-header">
                <h1>3 месяца</h1>
                </div>
                <div class="tarif__element-body">
                    <span>Безлимитный доступ ко всем упражнениям и разделам</span>
                    <span>900 Р</span>
                    <h1>490 Р</h1>
                </div>
            </div>
        </div>
            <a href="!#" class="button">Оплатить</a>
        </div>
        <div class="tarifs__body-space">
            <div class="tarif__element">
                <div class="tarif__element-header">
                <h1>6 месяцев</h1>
                </div>
                <div class="tarif__element-body">
                    <span>Безлимитный доступ ко всем упражнениям и разделам</span>
                    <span>1980 Р</span>
                    <h1>990 Р</h1>
                </div>
            </div>
            <a href="!#" class="button">Оплатить</a>
        </div>
        </div>
    </div>
</div>

<div class="tarif__pays">
    <div class="container">
        <h1>Доступные способы оплаты</h1>
        <div class="tarif__pays-rows">
            <a href=""><img class="tarifs_banner" src="{% static 'img/pays/Visapays.svg' %}" alt=""></a>
            <a href=""><img class="tarifs_banner" src="{% static 'img/pays/mastercardpays.svg' %}" alt=""></a>
            <a href=""><img class="tarifs_banner" src="{% static 'img/pays/ya_pays.svg' %}" alt=""></a>
            <a href=""><img class="tarifs_banner" src="{% static 'img/pays/qiwipays.svg' %}" alt=""></a>
            <a href=""><img class="tarifs_banner" src="{% static 'img/pays/PayPalpays.svg' %}" alt=""></a>
        </div>
    </div>
</div>
{% endblock tarifs %}

templates/app.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <title>Меморика - Главная</title>
</head>
<body>
    <section class="wrapper">
    {% include 'navigation.html'%}
    {% block profile %}{% endblock profile %}
    {% block game %}{% endblock game %}
    {% block tarifs %}{% endblock tarifs %}
    {% block header %}{% endblock header %} 
    {% block content %}{% endblock content %}
    {% block practice %}{% endblock practice %}
    {% include 'footer.html'%}
    </div>
</body>
<script src="{% static 'js/modal.js' %}"></script>
</html>

templates/footer.html
{% load static %}
<footer>
<div class="footer__landing">
    <div class="container">
        <div class="footer__map-row">
            <img src="{% static 'img/logo_black.svg' %}" alt="">
            <div class="map__element">
                <h1>О нас</h1>
                <a>Упражнения</a>
                <a>Блог</a>
                <a>Тарифы</a>
            </div>
            <div class="map__element">
                <h1>Условия и конфиденциальность</h1>
                <a>Правила сообщества</a>
                <a>Условия</a>
                <a>Конфиденциальность</a>
            </div>
            <div class="map__element">
                <h1>Мы в социальных<br>
                    сетях</h1>
                    <a>Telegram</a>
                    <a>Вконтакте</a>
                    <a>Однокласники</a>
            </div>
            <img src="{% static 'img/duck_book.svg' %}" alt="">
        </div>
    </div>
</div>
</footer>

templates/navigation.html
{% load static %}
<header>
<div class="container">
    <nav>
        <div class="nav__header">
        <a href="{% url 'landing:landing' %}">
          <img src="{% static 'img/logo_title.svg' %}">
        </a>
        <div class="navbar">
            <input type="checkbox" id="navbar-toggle" />
            <label for="navbar-toggle" class="navbar-toggle-icon"></label>
            <ul class="navbar-menu">
              <li>
                <a href="{% url 'traning:traning' %}">Упражнения</a>
              </li>
              <li>
                <a href="">Блог</a>
              </li>
              <li>
                <a href="{% url 'landing:tarifs' %}">Тарифы</a>
              </li>
            </ul>
          </div>
        {% if user.is_authenticated %}
        <a class="profile__circle" href="{% url 'account:profile' %}">
        
    </a>
</div>
        {% else %}
        <button id="openModalLogin" class="button blue" href="#!">
          Войти
        </button>
        {% endif %}
      </nav>
    <div id="registrationModal" class="modal">
        <div class="modal-content">
            <div class="modal__header">
                <img src="{% static 'img/memo_hello.svg' %}">
                    <h2>Регистрация</h2>
                    <div id="closeModal" class="button__close">
                        <span class="close">&times;</span>
                    </div>
            </div>
            <div class="modal__body">
                <div class="input__space">
                    <label for="emailInput">Email
                    </label>
                    <input type="email" name="email" id="emailInput" placeholder="email@gmail.com">
                </div>
                <button class="button orange" type="submit">Зарегистрироваться</button>
                <div class="social__row">
                    <div class="social__object blue">
                        <img src="{% static 'img/social/vk.svg' %}">
                    </div>
                    <div class="social__object">
                        <img src="{% static 'img/social/gmail.svg' %}">
                    </div>
                    <div class="social__object">
                        <img src="{% static 'img/social/ya.svg' %}">
                    </div>
                    <div class="social__object">
                        <img src="{% static 'img/social/apple.svg' %}">
                    </div>
                    <div class="social__object red">
                        <img src="{% static 'img/social/mts.svg' %}">
                    </div>
                </div>
                <button id="openloginModal" class="account" type="button">У меня уже есть аккаунт</button>
            </div>
        </div>
    </div>
    <form method="POST" action="{% url 'account:login' %}">
        {% csrf_token %}
    <div id="loginModal" class="modal">
        <div class="modal-content">
            <div class="modal__header">
                <img src="{% static 'img/memo_hello.svg' %}">
                    <h2>Вход в Storiqa School</h2>
                    <div id="closeModal" class="button__close">
                        <span class="close">&times;</span>
                    </div>
            </div>
            <div class="modal__body">
                {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
                <div class="input__space">
                    <label for="emailInputSecond">Email
                    </label>
                    <input type="email" name="email" id="emailInputSecond" placeholder="email@gmail.com">
                </div>
                <div class="input__space">
                    <label for="passwordInput">Пароль
                    </label>
                    <input type="password" name="password" id="passwordInput" placeholder="Пароль">
                </div>
                <button class="button orange" type="submit">Войти</button>
                <div class="social__row">
                    <div class="social__object blue">
                        <img src="{% static 'img/social/vk.svg' %}">
                    </div>
                    <div class="social__object">
                        <img src="{% static 'img/social/gmail.svg' %}">
                    </div>
                    <div class="social__object">
                        <img src="{% static 'img/social/ya.svg' %}">
                    </div>
                    <div class="social__object">
                        <img src="{% static 'img/social/apple.svg' %}">
                    </div>
                    <div class="social__object red">
                        <img src="{% static 'img/social/mts.svg' %}">
                    </div>
                </div>
                <button id="registrationModalOpen" class="account" type="button">У меня нет аккаунта</button>
            </div>
        </div>
    </div>
</form>
</div>
</header>

traning/templates/traning/alphabet_layout.html
{% extends 'app.html' %}
{% load static %}
{% block practice %}
<div class="traning__header">
    <div class="container">
        <div class="traning__header-selected blue row">
            <div class="tranin-header-left">
            <h1>Алфавит для детей</h1>
            <div class="traning__header-row">
                <div class="traning__header-column">
                    <article>Всего 15 минут занятий в день в течении 3-х месяцев
                        и ваш ребенок начнет читать</article>
                    <div class="traning__header-row">
                        <select class="blue" name="" id="">
                            <option>Выберите возраст</option>
                        </select>
                        <select class="orange" name="" id="">
                            <option>Выберите возраст</option>
                        </select>
                    </div>
                </div>
            </div>
            </div>
            <img class="memo__book" src="{% static 'img/duck_book.svg' %}" alt="">
        </div>
        <div class="traning__header-selected blue alph-bg">
            <div class="traning__header-alph">
                <div class="alph__element">
                    <div class="alph__element-letter blue">
                        <h1>A</h1>
                        <img src="{% static 'img/a.svg' %}">
                    </div>
                    <div class="letter__name">
                        <span>Буква А</span>
                    </div>
                </div>
                <div class="alph__element">
                    <div class="alph__element-letter green">
                        <h1>Б</h1>
                        <img src="{% static 'img/b.svg' %}">
                    </div>
                    <div class="letter__name">
                        <span>Буква Б</span>
                    </div>
                </div>
                <div class="alph__element">
                    <div class="alph__element-letter orange-3">
                        <h1>В</h1>
                        <img src="{% static 'img/v.svg' %}">
                    </div>
                    <div class="letter__name">
                        <span>Буква В</span>
                    </div>
                </div>
                <div class="alph__element">
                    <div class="alph__element-letter blue-2">
                        <h1>Г</h1>
                        <img src="{% static 'img/g.svg' %}">
                    </div>
                    <div class="letter__name">
                        <span>Буква Г</span>
                    </div>
                </div>
                <div class="alph__element">
                    <div class="alph__element-letter red">
                        <h1>Д</h1>
                        <img src="{% static 'img/d.svg' %}">
                    </div>
                    <div class="letter__name">
                        <span>Буква Д</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="traning__header-selected blue-2 quest-bg">
            <div class="traning-header-left">
            <h1>С чего начать изучение алфавита?</h1>
            <div class="traning__header-row information">
                <div class="training__header-column">
                    <article>Чтение - это один из самых важных навыков, которые человек может 
                        освоить в жизни. Оно дает нам возможность учиться, общаться, 
                        познавать мир и наслаждаться книгами. Но чтобы научиться читать, нужно потратить время и усилия на тренировку. <br><br>Эти навыки пригодятся во многих сферах жизни, начиная от учебы и 
                        заканчивая работой. Именно поэтому так важно научить детей читать с раннего возраста и помочь им развивать этот навык на протяжении всей жизни.</article>
                </div>
            </div>
        </div>
        <img src="{% static 'img/duck_2.svg' %}" alt="">
        </div>
    </div>
</div>
{% endblock practice %}

traning/templates/traning/games/alphabet.html
{% extends 'app.html' %}
{% load static %}
{% block game %}
<div class="game__container">
    <div class="container">
        <h1>Игра Алфавит</h1>
        <div class="game__body">
        <form method="POST">
            {% csrf_token %}
            <div class="game__body-form">
            <span>Выбери букву {{ correct_letter }} </span>
            <div class="game__body-selected">
            {% for letter in letters %}
            <div class="letter__object">
                <input class="letter__select"type="radio" name="letter" value="{{ letter }}" required>
    
            <div class="selected__radio">
                <label for="{{ letter.id }}">{{ letter }}</label>
            </div>
            </div>
            {% endfor %}
        </div>
        </div>
        </form>
    </div>
    </div>
</div>
{% endblock game %}

traning/templates/traning/main.html
{% extends 'app.html' %}
{% load static %}
{% block practice %}
<div class="traning__header">
    <div class="container">
        <div class="traning__header-selected green-bg row">
            <div class="tranin-header-left">
            <h1>Обучение чтению детей</h1>
            <div class="traning__header-row">
                <div class="traning__header-column">
                    <article>Всего 15 минут занятий в день в течении 3-х месяцев
                        и ваш ребенок начнет читать</article>
                        <form method="POST">
                            {% csrf_token %}
                    <div class="traning__header-row">
                        <select class="blue" name="age" id="ageSelect" required>
                            <option>Выберите возраст</option>
                            {% for age in game_age %}
                            <option value="{{ age.id }}">{{ age.age_name }}</option>
                            {% endfor %}
                        </select>
                        <select class="orange" name="game" id="gameSelect" required>
                            <option value="1">Чтение для детей</option>
                            <option value="2">Звуки для детей</option>
                        </select>

                    </div>
                    <button class="button green" type="submit">Начать</button>
                </form>
                </div>
            </div>
            </div>
            <img class="memo__book" src="{% static 'img/duck_book.svg' %}" alt="">
        </div>
        <div class="traning__header-selected blue alph-bg">
            <div class="traning__header-title">
            <h1>Алфавит для детей</h1>
            <a href="{% url 'traning:alphabet' %}">Посмотреть все</a>
        </div>
            <div class="traning__header-alph">
                <div class="alph__element">
                    <div class="alph__element-letter blue">
                        <h1>A</h1>
                        <img src="{% static 'img/a.svg' %}">
                    </div>
                    <div class="letter__name">
                        <span>Буква А</span>
                    </div>
                </div>
                <div class="alph__element">
                    <div class="alph__element-letter green">
                        <h1>Б</h1>
                        <img src="{% static 'img/b.svg' %}">
                    </div>
                    <div class="letter__name">
                        <span>Буква Б</span>
                    </div>
                </div>
                <div class="alph__element">
                    <div class="alph__element-letter orange-3">
                        <h1>В</h1>
                        <img src="{% static 'img/v.svg' %}">
                    </div>
                    <div class="letter__name">
                        <span>Буква В</span>
                    </div>
                </div>
                <div class="alph__element">
                    <div class="alph__element-letter blue-2">
                        <h1>Г</h1>
                        <img src="{% static 'img/g.svg' %}">
                    </div>
                    <div class="letter__name">
                        <span>Буква Г</span>
                    </div>
                </div>
                <div class="alph__element">
                    <div class="alph__element-letter red">
                        <h1>Д</h1>
                        <img src="{% static 'img/d.svg' %}">
                    </div>
                    <div class="letter__name">
                        <span>Буква Д</span>
                    </div>
                </div>
                <a href="{% url 'traning:alphabet' %}" class="alph__element">
                    <div class="alph__element-letter green more">
                        <h1>Посмотреть<br>
                            все<br>
                            задания</h1>
                    </div>
                </a>
            </div>
        </div>
        <div class="traning__header-selected orange voices-bg">
            <div class="traning__header-title">
            <h1>Звуки для детей</h1>
            <a href="{% url 'traning:sounds' %}">Посмотреть все</a>
        </div>
            <div class="traning__header-alph">
                <div class="alph__element voices">
                    <div class="alph__element-letter orange">
                        <img src="{% static 'img/voices/letter_1.svg' %}">
                    </div>
                    <div class="letter__name">
                        <span>Изучаем<br> гласные буквы</span>
                    </div>
                </div>
                <div class="alph__element voices">
                    <div class="alph__element-letter blue">
                        <img src="{% static 'img/voices/letter_2.svg' %}">
                    </div>
                    <div class="letter__name">
                        <span>Различаем гласные
                            и согласные звуки</span>
                    </div>
                </div>
                <div class="alph__element voices">
                    <div class="alph__element-letter green-light">
                        <img src="{% static 'img/voices/letter_3.svg' %}">
                    </div>
                    <div class="letter__name">
                        <span>Твердые и мягкие 
                            согласные звуки</span>
                    </div>
                </div>
                <div class="alph__element voices">
                    <div class="alph__element-letter purple">
                        <img src="{% static 'img/voices/letter_4.svg' %}">
                    </div>
                    <div class="letter__name">
                        <span>Различаем буквы</span>
                    </div>
                </div>
                <div class="alph__element voices">
                    <div class="alph__element-letter green">
                        <img src="{% static 'img/voices/letter_5.svg' %}">
                    </div>
                    <div class="letter__name">
                        <span>Буквенные пазлы</span>
                    </div>
                </div>
                <a href="{% url 'traning:sounds' %}" class="alph__element voices">
                    <div class="alph__element-letter orange more__orange">
                        <h1>Посмотреть<br>
                            все<br>
                            задания</h1>
                    </div>
                </a>
            </div>
        </div>
        <div class="traning__header-selected blue-2 quest-bg">
            <div class="traning-header-left">
            <h1>Как научить ребенка читать?</h1>
            <div class="traning__header-row information">
                <div class="training__header-column">
                    <article>Чтение - это один из самых важных навыков, которые человек может 
                        освоить в жизни. Оно дает нам возможность учиться, общаться, 
                        познавать мир и наслаждаться книгами. Но чтобы научиться читать, нужно потратить время и усилия на тренировку. 
                    </article>
                    <article>
                        Эти навыки пригодятся во многих сферах жизни, начиная от учебы и 
                        заканчивая работой.<br> Именно поэтому так важно научить детей читать с раннего возраста и помочь им развивать этот навык на протяжении всей жизни.</article>
                </div>
            </div>
        </div>
        <img src="{% static 'img/duck_2.svg' %}" alt="">
        </div>
    </div>
</div>
    {% endblock practice %}